const DB='invoice-capture-db',RS='records',SS='settings',DEFAULT_FILE='invoice-summary.csv';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const el={tabs:$$('.tab'),panels:{scan:$('#scanPanel'),records:$('#recordsPanel'),settings:$('#settingsPanel')},image:$('#imageInput'),preview:$('#previewImage'),extract:$('#extractButton'),manual:$('#manualButton'),scanForm:$('#scanForm'),review:$('#reviewForm'),status:$('#reviewStatus'),num:$('#invoiceNumber'),date:$('#invoiceDate'),amount:$('#totalAmount'),tax:$('#buyerTaxId'),taxResult:$('#taxIdResult'),include:$('#includeInTotal'),dup:$('#duplicateWarning'),clear:$('#clearReviewButton'),count:$('#includedCount'),total:$('#includedTotal'),dupCount:$('#duplicateCount'),list:$('#recordList'),settingsForm:$('#settingsForm'),target:$('#targetTaxId'),filename:$('#exportFilename'),export:$('#exportButton'),import:$('#importInput'),toast:$('#toast'),install:$('#installButton')};
let db,settings={targetTaxId:'',exportFilename:DEFAULT_FILE},imageData='',editId='',installPrompt=null;
function openDb(){return new Promise((ok,fail)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(RS)){const s=d.createObjectStore(RS,{keyPath:'id'});s.createIndex('invoiceNumber','invoiceNumber')}if(!d.objectStoreNames.contains(SS))d.createObjectStore(SS,{keyPath:'key'})};r.onsuccess=()=>ok(r.result);r.onerror=()=>fail(r.error)})}
function store(n,m='readonly'){return db.transaction(n,m).objectStore(n)}
function req(r){return new Promise((ok,fail)=>{r.onsuccess=()=>ok(r.result);r.onerror=()=>fail(r.error)})}
const all=()=>req(store(RS).getAll()),save=x=>req(store(RS,'readwrite').put(x)),del=id=>req(store(RS,'readwrite').delete(id));
async function loadSettings(){const row=await req(store(SS).get('settings'));settings={...settings,...(row?.value||{})};el.target.value=settings.targetTaxId;el.filename.value=settings.exportFilename||DEFAULT_FILE}
async function saveSettings(){await req(store(SS,'readwrite').put({key:'settings',value:settings}))}
function toast(t){el.toast.textContent=t;el.toast.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>el.toast.hidden=true,2600)}
const money=n=>Number(n||0).toLocaleString('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0});
const tax=v=>String(v||'').replace(/\D/g,'').slice(0,8),inv=v=>String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,10),amt=v=>{const d=String(v||'').replace(/[^\d]/g,'');return d?String(Number(d)):''};
function taxOk(){const a=tax(settings.targetTaxId),b=tax(el.tax.value);return !!(a&&b&&a===b)}
function updateTax(){const a=tax(settings.targetTaxId),b=tax(el.tax.value);if(!a){el.taxResult.textContent='尚未設定';el.include.checked=false;return}if(!b){el.taxResult.textContent='未辨識';el.include.checked=false;return}const ok=a===b;el.taxResult.textContent=ok?'正確':'不符合';el.taxResult.className=ok?'ok':'warn';if(!ok)el.include.checked=false}
function review(d={}){el.num.value=inv(d.invoiceNumber);el.date.value=d.invoiceDate||'';el.amount.value=amt(d.totalAmount);el.tax.value=tax(d.buyerTaxId);el.include.checked=!!d.includeInTotal;el.status.textContent=d.status||'請確認辨識結果';el.review.hidden=false;updateTax();checkDup()}
function clearReview(){editId='';imageData='';el.image.value='';el.preview.hidden=true;el.preview.removeAttribute('src');review({status:'請輸入或辨識發票資料'});el.review.hidden=true;el.dup.hidden=true}
function fileUrl(f){return new Promise((ok,fail)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=()=>fail(r.error);r.readAsDataURL(f)})}
async function qr(file){if(!('BarcodeDetector'in window))return{};try{const det=new BarcodeDetector({formats:['qr_code']}),bm=await createImageBitmap(file),codes=await det.detect(bm);bm.close?.();return parseQr(codes.map(c=>c.rawValue).join('\n'))}catch{return{}}}
function parseQr(raw){const t=String(raw||''),m=t.match(/[A-Z]{2}\d{8}/),hex=[...t.matchAll(/[:*]([0-9A-Fa-f]{8})[:*]/g)].map(x=>x[1]),ids=[...t.matchAll(/\b\d{8}\b/g)].map(x=>x[0]),dm=t.match(/(?:[A-Z]{2}\d{8})(\d{7})/);return{invoiceNumber:m?.[0]||'',invoiceDate:dm?roc(dm[1]):'',totalAmount:hex.length>=2?String(parseInt(hex[1],16)):'',buyerTaxId:ids.find(x=>x===settings.targetTaxId)||''}}
function roc(v){if(!/^\d{7}$/.test(v))return'';return `${Number(v.slice(0,3))+1911}-${v.slice(3,5)}-${v.slice(5,7)}`}
async function extract(){const f=el.image.files?.[0];if(!f)return;el.extract.disabled=true;el.extract.textContent='辨識中';const data=await qr(f),has=Object.values(data).some(Boolean);data.includeInTotal=tax(data.buyerTaxId)===tax(settings.targetTaxId);data.status=has?'已讀取 QR 資料，請確認':'未讀取到 QR，請手動輸入';review(data);el.extract.disabled=false;el.extract.textContent='辨識發票'}
async function dupInfo(n,d,a){const rs=await all(),no=inv(n);if(no){const x=rs.find(r=>r.id!==editId&&r.invoiceNumber===no);if(x)return{type:'exact',record:x}}if(d&&a){const x=rs.find(r=>r.id!==editId&&r.invoiceDate===d&&String(r.totalAmount)===String(a));if(x)return{type:'possible',record:x}}return null}
async function checkDup(){const d=await dupInfo(el.num.value,el.date.value,amt(el.amount.value));el.dup.hidden=!d;el.dup.textContent=d?(d.type==='exact'?`發票號碼已存在：${d.record.invoiceNumber}，儲存時會再次確認。`:'可能重複：同日期與同金額已有一筆記錄。'):''}
async function submit(e){e.preventDefault();const invoiceNumber=inv(el.num.value),invoiceDate=el.date.value,totalAmount=amt(el.amount.value),buyerTaxId=tax(el.tax.value),matched=!!(buyerTaxId&&settings.targetTaxId&&buyerTaxId===settings.targetTaxId),include=!!(el.include.checked&&matched);if(!invoiceDate||!totalAmount)return toast('日期與總金額必填');const d=await dupInfo(invoiceNumber,invoiceDate,totalAmount);let flag=d?.type||'';if(d?.type==='exact'){if(confirm('發票號碼已存在。按「確定」覆蓋原記錄，按「取消」仍新增並標記重複。'))editId=d.record.id;else flag='exact'}else if(d?.type==='possible'&&!confirm('同日期與同金額已有記錄，可能重複。仍要新增嗎？'))return;const now=new Date().toISOString();await save({id:editId||crypto.randomUUID(),invoiceNumber,invoiceDate,totalAmount:Number(totalAmount),buyerTaxId,taxIdMatched:matched,includeInTotal:include,duplicateFlag:flag,createdAt:now,updatedAt:now});toast('已儲存記錄');clearReview();render()}
async function render(){const rs=(await all()).sort((a,b)=>String(b.invoiceDate).localeCompare(String(a.invoiceDate))||String(b.createdAt).localeCompare(String(a.createdAt))),inc=rs.filter(r=>r.taxIdMatched&&r.includeInTotal),sum=inc.reduce((s,r)=>s+Number(r.totalAmount||0),0);el.count.textContent=inc.length;el.total.textContent=money(sum);el.dupCount.textContent=rs.filter(r=>r.duplicateFlag).length;el.list.innerHTML=rs.length?rs.map(card).join(''):'<div class="status-line">尚無記錄</div>'}
function card(r){return `<article class="record-card" data-id="${r.id}"><div class="record-top"><strong>${money(r.totalAmount)}</strong><span>${r.invoiceDate||''}</span></div><div><span class="badge">${r.invoiceNumber||'無發票號碼'}</span> <span class="badge ${r.taxIdMatched?'ok':'warn'}">${r.taxIdMatched?'統編正確':'統編不符'}</span> <span class="badge">${r.includeInTotal?'納入加總':'未納入'}</span> ${r.duplicateFlag?'<span class="badge warn">重複提示</span>':''}</div><div class="record-meta"><span>發票統編：${r.buyerTaxId||'未填'}</span><span>更新：${new Date(r.updatedAt||r.createdAt).toLocaleDateString('zh-TW')}</span></div><div class="record-actions"><button class="secondary" data-action="toggle">${r.includeInTotal?'排除':'納入'}</button><button class="secondary" data-action="edit">編輯</button><button class="secondary" data-action="delete">刪除</button></div></article>`}
function csvCell(v){return `"${String(v??'').replaceAll('"','""')}"`}
function csv(rs){const rows=[['發票號碼','發票日期','單張總金額','統編是否正確','是否納入加總'],...rs.map(r=>[r.invoiceNumber,r.invoiceDate,r.totalAmount,r.taxIdMatched?'是':'否',r.includeInTotal?'是':'否'])],sum=rs.filter(r=>r.taxIdMatched&&r.includeInTotal).reduce((s,r)=>s+Number(r.totalAmount||0),0);rows.push(['','加總',sum,'','']);return rows.map(r=>r.map(csvCell).join(',')).join('\n')}
async function exportCsv(){const blob=new Blob(['\ufeff'+csv(await all())],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=settings.exportFilename||DEFAULT_FILE;a.click();URL.revokeObjectURL(url);toast('已產生固定檔名匯出檔')}
function parseCsv(t){const rows=[];let row=[],cell='',q=false;for(let i=0;i<t.length;i++){const c=t[i],n=t[i+1];if(q&&c==='"'&&n==='"'){cell+='"';i++}else if(c==='"')q=!q;else if(!q&&c===','){row.push(cell);cell=''}else if(!q&&(c==='\n'||c==='\r')){if(c==='\r'&&n==='\n')i++;row.push(cell);rows.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
async function importCsv(f){const rows=parseCsv((await f.text()).replace(/^\ufeff/,''));let c=0;for(const r of rows.slice(1)){if(r[1]==='加總'||!r[1]||!r[2])continue;await save({id:crypto.randomUUID(),invoiceNumber:inv(r[0]),invoiceDate:r[1],totalAmount:Number(amt(r[2])),buyerTaxId:'',taxIdMatched:r[3]==='是',includeInTotal:r[4]==='是',duplicateFlag:'',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});c++}toast(`已匯入 ${c} 筆`);render()}
async function recordAction(e){const b=e.target.closest('button[data-action]');if(!b)return;const id=b.closest('.record-card')?.dataset.id,r=(await all()).find(x=>x.id===id);if(!r)return;if(b.dataset.action==='delete'){if(confirm('確定刪除此筆記錄？')){await del(id);toast('已刪除');render()}}if(b.dataset.action==='toggle'){r.includeInTotal=!r.includeInTotal&&r.taxIdMatched;r.updatedAt=new Date().toISOString();await save(r);render()}if(b.dataset.action==='edit'){editId=r.id;tab('scan');review({...r,status:'編輯既有記錄'})}}
function tab(name){el.tabs.forEach(t=>t.classList.toggle('is-active',t.dataset.tab===name));Object.entries(el.panels).forEach(([k,p])=>p.classList.toggle('is-active',k===name))}
function bind(){el.tabs.forEach(t=>t.onclick=()=>tab(t.dataset.tab));el.image.onchange=async()=>{const f=el.image.files?.[0];if(!f)return;imageData=await fileUrl(f);el.preview.src=imageData;el.preview.hidden=false;el.extract.disabled=false};el.scanForm.onsubmit=e=>{e.preventDefault();extract()};el.manual.onclick=()=>review({status:'手動新增發票資料'});el.review.onsubmit=submit;el.clear.onclick=clearReview;[el.tax,el.num,el.date,el.amount].forEach(i=>i.oninput=()=>{if(i===el.tax){el.tax.value=tax(el.tax.value);updateTax()}if(i===el.amount)el.amount.value=amt(el.amount.value);if(i===el.num)el.num.value=inv(el.num.value);checkDup()});el.include.onchange=()=>{if(el.include.checked&&!taxOk()){el.include.checked=false;toast('統編正確才可納入加總')}};el.settingsForm.onsubmit=async e=>{e.preventDefault();settings.targetTaxId=tax(el.target.value);settings.exportFilename=el.filename.value.trim()||DEFAULT_FILE;el.target.value=settings.targetTaxId;await saveSettings();updateTax();toast('設定已儲存')};el.export.onclick=exportCsv;el.import.onchange=async()=>{const f=el.import.files?.[0];if(f)await importCsv(f);el.import.value=''};el.list.onclick=recordAction;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;el.install.hidden=false});el.install.onclick=async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;el.install.hidden=true}}
(async()=>{db=await openDb();await loadSettings();bind();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})})().catch(e=>toast(e.message||'App 啟動失敗'));
